// <auto-generated />
using System;
using System.Collections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Sombra.CharityActionService.DAL;

namespace Sombra.CharityService.Migrations
{
    [DbContext(typeof(CharityActionContext))]
    partial class CharityActionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sombra.CharityActionService.DAL.CharityActionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Charitykey");

                    b.Property<ICollection>("UsersKey");

                    b.Property<string>("NameAction");

                    b.Property<string>("ActionType");

                    b.Property<string>("Story");

                    b.HasKey("Id");

                    b.ToTable("CharityActions");
                });
#pragma warning restore 612, 618
        }
    }
}